from .models import Meal, MealIngredient

MEAL_DATA = [
    {
        "name": 'Greek yogurt with granola and berries',
        "description": 'Creamy Greek yogurt layered with crunchy granola and fresh berries.',
        "instructions": 'Layer yogurt in a bowl. Top with granola and berries. Drizzle with honey.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 1,
        "calories": 374.8,
        "protein_g": 27.0,
        "carbs_g": 25.3,
        "fats_g": 27.0,
        "iron_mg": 4.8,
        "calcium_mg": 222.5,
        "vitamin_c_mg": 46.2,
        "vitamin_d_iu": 168.3,
        "ingredients": [
            {"name": 'Greek yogurt', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'granola', "quantity": 0.5, "unit": 'cup', "category": 'grains'},
            {"name": 'mixed berries', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Scrambled eggs with toast',
        "description": 'Fluffy scrambled eggs served alongside crispy whole wheat toast.',
        "instructions": 'Whisk eggs. Cook in buttered pan over medium heat, stirring gently. Toast bread. Serve together.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 622.4,
        "protein_g": 22.7,
        "carbs_g": 20.6,
        "fats_g": 23.0,
        "iron_mg": 5.1,
        "calcium_mg": 397.7,
        "vitamin_c_mg": 37.3,
        "vitamin_d_iu": 252.0,
        "ingredients": [
            {"name": 'eggs', "quantity": 2.0, "unit": 'each', "category": 'meat'},
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'butter', "quantity": 1.0, "unit": 'tbsp', "category": 'dairy'},
            {"name": 'salt', "quantity": 0.25, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Oatmeal with banana and peanut butter',
        "description": 'Warm creamy oats topped with banana slices and a spoonful of peanut butter.',
        "instructions": 'Cook oats with milk per package. Top with sliced banana and peanut butter. Drizzle honey.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 480.0,
        "protein_g": 28.7,
        "carbs_g": 18.9,
        "fats_g": 17.7,
        "iron_mg": 4.9,
        "calcium_mg": 305.0,
        "vitamin_c_mg": 75.7,
        "vitamin_d_iu": 288.9,
        "ingredients": [
            {"name": 'rolled oats', "quantity": 0.5, "unit": 'cup', "category": 'grains'},
            {"name": 'banana', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'peanut butter', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
            {"name": 'milk', "quantity": 0.5, "unit": 'cup', "category": 'dairy'},
        ],
    },
    {
        "name": 'Egg and cheese breakfast burrito',
        "description": 'Scrambled eggs and melted cheese wrapped in a soft flour tortilla.',
        "instructions": 'Scramble eggs with pepper. Warm tortilla. Fill with eggs, cheese, and salsa. Roll up.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 495.8,
        "protein_g": 25.5,
        "carbs_g": 22.2,
        "fats_g": 20.5,
        "iron_mg": 4.5,
        "calcium_mg": 281.4,
        "vitamin_c_mg": 17.6,
        "vitamin_d_iu": 264.3,
        "ingredients": [
            {"name": 'eggs', "quantity": 2.0, "unit": 'each', "category": 'meat'},
            {"name": 'flour tortilla', "quantity": 1.0, "unit": 'each', "category": 'grains'},
            {"name": 'cheddar cheese', "quantity": 0.25, "unit": 'cup', "category": 'dairy'},
            {"name": 'salsa', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'bell pepper', "quantity": 0.25, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Whole grain pancakes with fruit',
        "description": 'Light and fluffy whole grain pancakes topped with fresh mixed fruit.',
        "instructions": 'Mix dry ingredients. Whisk in wet. Pour onto griddle. Flip when bubbles form. Top with fruit.',
        "meal_type": 'breakfast',
        "prep_time": 10,
        "cook_time": 15,
        "servings": 2,
        "calories": 489.0,
        "protein_g": 34.5,
        "carbs_g": 17.2,
        "fats_g": 21.3,
        "iron_mg": 5.7,
        "calcium_mg": 266.8,
        "vitamin_c_mg": 21.6,
        "vitamin_d_iu": 273.2,
        "ingredients": [
            {"name": 'whole wheat flour', "quantity": 1.0, "unit": 'cup', "category": 'grains'},
            {"name": 'eggs', "quantity": 1.0, "unit": 'each', "category": 'meat'},
            {"name": 'milk', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'baking powder', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
            {"name": 'mixed fruit', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
        ],
    },
    {
        "name": 'Cottage cheese with pineapple',
        "description": 'Light and protein-rich cottage cheese paired with sweet pineapple chunks.',
        "instructions": 'Scoop cottage cheese into a bowl. Top with pineapple and a drizzle of honey.',
        "meal_type": 'breakfast',
        "prep_time": 3,
        "cook_time": 0,
        "servings": 1,
        "calories": 521.6,
        "protein_g": 27.1,
        "carbs_g": 22.2,
        "fats_g": 21.5,
        "iron_mg": 4.9,
        "calcium_mg": 196.6,
        "vitamin_c_mg": 32.7,
        "vitamin_d_iu": 185.0,
        "ingredients": [
            {"name": 'cottage cheese', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'pineapple chunks', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Avocado toast with eggs',
        "description": 'Creamy mashed avocado on toasted bread topped with perfectly cooked eggs.',
        "instructions": 'Toast bread. Mash avocado with lemon juice. Fry or poach eggs. Assemble and season.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 549.8,
        "protein_g": 28.0,
        "carbs_g": 12.8,
        "fats_g": 15.8,
        "iron_mg": 4.5,
        "calcium_mg": 252.5,
        "vitamin_c_mg": 44.2,
        "vitamin_d_iu": 209.9,
        "ingredients": [
            {"name": 'whole grain bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'avocado', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'eggs', "quantity": 2.0, "unit": 'each', "category": 'meat'},
            {"name": 'lemon juice', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
            {"name": 'red pepper flakes', "quantity": 0.25, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Protein smoothie with spinach',
        "description": 'Nutrient-packed green smoothie blended with protein powder and banana.',
        "instructions": 'Add all ingredients to blender. Blend until smooth. Serve immediately.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 1,
        "calories": 356.0,
        "protein_g": 22.5,
        "carbs_g": 14.7,
        "fats_g": 22.9,
        "iron_mg": 4.6,
        "calcium_mg": 261.8,
        "vitamin_c_mg": 37.7,
        "vitamin_d_iu": 172.7,
        "ingredients": [
            {"name": 'spinach', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
            {"name": 'protein powder', "quantity": 1.0, "unit": 'scoop', "category": 'pantry'},
            {"name": 'banana', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'almond milk', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'chia seeds', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Honey topped coffee and cream with eggs',
        "description": 'Rich coffee with cream and honey alongside soft cooked eggs.',
        "instructions": 'Brew coffee. Add cream and honey. Fry or scramble eggs separately. Serve together.',
        "meal_type": 'breakfast',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 476.8,
        "protein_g": 25.0,
        "carbs_g": 18.7,
        "fats_g": 17.4,
        "iron_mg": 4.9,
        "calcium_mg": 333.8,
        "vitamin_c_mg": 52.5,
        "vitamin_d_iu": 254.3,
        "ingredients": [
            {"name": 'coffee', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'heavy cream', "quantity": 2.0, "unit": 'tbsp', "category": 'dairy'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'eggs', "quantity": 2.0, "unit": 'each', "category": 'meat'},
        ],
    },
    {
        "name": 'Whole grain cereal with milk',
        "description": 'Crunchy whole grain cereal served cold with milk and sliced banana.',
        "instructions": 'Pour cereal into bowl. Add cold milk. Top with banana slices. Serve immediately.',
        "meal_type": 'breakfast',
        "prep_time": 2,
        "cook_time": 0,
        "servings": 1,
        "calories": 598.6,
        "protein_g": 29.7,
        "carbs_g": 14.5,
        "fats_g": 21.1,
        "iron_mg": 5.1,
        "calcium_mg": 238.7,
        "vitamin_c_mg": 42.2,
        "vitamin_d_iu": 214.5,
        "ingredients": [
            {"name": 'whole grain cereal', "quantity": 1.0, "unit": 'cup', "category": 'grains'},
            {"name": 'milk', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'banana', "quantity": 0.5, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Peanut butter and jelly sandwich',
        "description": 'Classic PB&J on whole wheat with an apple and baby carrots on the side.',
        "instructions": 'Spread peanut butter on one slice and jam on the other. Sandwich together. Serve with apple and carrots.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 2,
        "calories": 545.6,
        "protein_g": 24.2,
        "carbs_g": 21.8,
        "fats_g": 19.9,
        "iron_mg": 3.6,
        "calcium_mg": 302.2,
        "vitamin_c_mg": 44.0,
        "vitamin_d_iu": 247.6,
        "ingredients": [
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'peanut butter', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'strawberry jam', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'apple', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'baby carrots', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
        ],
    },
    {
        "name": 'Turkey and cheese wrap',
        "description": 'Sliced turkey and cheddar cheese wrapped in a soft tortilla with fresh veggies.',
        "instructions": 'Lay tortilla flat. Layer turkey, cheese, lettuce, and tomato. Roll tightly and slice.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 2,
        "calories": 654.8,
        "protein_g": 22.5,
        "carbs_g": 15.4,
        "fats_g": 27.3,
        "iron_mg": 6.5,
        "calcium_mg": 202.8,
        "vitamin_c_mg": 48.8,
        "vitamin_d_iu": 190.1,
        "ingredients": [
            {"name": 'flour tortilla', "quantity": 1.0, "unit": 'each', "category": 'grains'},
            {"name": 'turkey slices', "quantity": 3.0, "unit": 'oz', "category": 'meat'},
            {"name": 'cheddar cheese', "quantity": 1.0, "unit": 'oz', "category": 'dairy'},
            {"name": 'lettuce', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'tomato', "quantity": 0.25, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Chicken salad with greens',
        "description": 'Grilled chicken over a bed of fresh mixed greens with a light olive oil dressing.',
        "instructions": 'Slice grilled chicken. Arrange over greens with tomatoes and cucumber. Drizzle with olive oil.',
        "meal_type": 'lunch',
        "prep_time": 10,
        "cook_time": 0,
        "servings": 2,
        "calories": 672.8,
        "protein_g": 24.8,
        "carbs_g": 29.0,
        "fats_g": 24.9,
        "iron_mg": 6.0,
        "calcium_mg": 277.9,
        "vitamin_c_mg": 59.5,
        "vitamin_d_iu": 221.2,
        "ingredients": [
            {"name": 'grilled chicken breast', "quantity": 4.0, "unit": 'oz', "category": 'meat'},
            {"name": 'mixed greens', "quantity": 2.0, "unit": 'cup', "category": 'produce'},
            {"name": 'cherry tomatoes', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'cucumber', "quantity": 0.25, "unit": 'each', "category": 'produce'},
            {"name": 'olive oil', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Ham sandwich with fruit',
        "description": 'Classic ham and Swiss sandwich on whole wheat with fresh fruit on the side.',
        "instructions": 'Layer ham, cheese, and mustard between bread slices. Serve with sliced apple.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 2,
        "calories": 514.6,
        "protein_g": 17.7,
        "carbs_g": 22.5,
        "fats_g": 27.0,
        "iron_mg": 4.1,
        "calcium_mg": 306.9,
        "vitamin_c_mg": 41.8,
        "vitamin_d_iu": 232.9,
        "ingredients": [
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'ham slices', "quantity": 3.0, "unit": 'oz', "category": 'meat'},
            {"name": 'Swiss cheese', "quantity": 1.0, "unit": 'oz', "category": 'dairy'},
            {"name": 'mustard', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
            {"name": 'apple', "quantity": 1.0, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Bean and rice bowl',
        "description": 'Hearty brown rice and black beans bowl with corn, salsa, and a dollop of sour cream.',
        "instructions": 'Cook rice per package. Warm beans and corn. Layer in bowl. Top with salsa and sour cream.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 20,
        "servings": 2,
        "calories": 488.6,
        "protein_g": 15.7,
        "carbs_g": 13.8,
        "fats_g": 18.5,
        "iron_mg": 4.5,
        "calcium_mg": 289.9,
        "vitamin_c_mg": 45.1,
        "vitamin_d_iu": 183.1,
        "ingredients": [
            {"name": 'brown rice', "quantity": 0.75, "unit": 'cup', "category": 'grains'},
            {"name": 'black beans', "quantity": 0.5, "unit": 'cup', "category": 'pantry'},
            {"name": 'corn', "quantity": 0.25, "unit": 'cup', "category": 'produce'},
            {"name": 'salsa', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'sour cream', "quantity": 1.0, "unit": 'tbsp', "category": 'dairy'},
        ],
    },
    {
        "name": 'Chicken quesadilla',
        "description": 'Crispy flour tortilla filled with grilled chicken, melted cheddar, and peppers.',
        "instructions": 'Place chicken and cheese on half the tortilla. Fold. Cook in pan 2-3 min per side. Slice and serve with salsa.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 559.0,
        "protein_g": 24.7,
        "carbs_g": 22.5,
        "fats_g": 27.2,
        "iron_mg": 4.6,
        "calcium_mg": 229.1,
        "vitamin_c_mg": 29.3,
        "vitamin_d_iu": 150.3,
        "ingredients": [
            {"name": 'flour tortillas', "quantity": 2.0, "unit": 'each', "category": 'grains'},
            {"name": 'grilled chicken', "quantity": 3.0, "unit": 'oz', "category": 'meat'},
            {"name": 'cheddar cheese', "quantity": 0.5, "unit": 'cup', "category": 'dairy'},
            {"name": 'salsa', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'bell pepper', "quantity": 0.5, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Tuna salad sandwich',
        "description": 'Creamy tuna salad on whole wheat bread with crunchy celery.',
        "instructions": 'Mix tuna with mayo, celery, and lemon juice. Spread on bread slices. Sandwich and serve.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 2,
        "calories": 327.2,
        "protein_g": 29.0,
        "carbs_g": 20.2,
        "fats_g": 6.7,
        "iron_mg": 4.6,
        "calcium_mg": 330.2,
        "vitamin_c_mg": 43.3,
        "vitamin_d_iu": 154.2,
        "ingredients": [
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'canned tuna', "quantity": 5.0, "unit": 'oz', "category": 'meat'},
            {"name": 'mayonnaise', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'celery', "quantity": 2.0, "unit": 'stalk', "category": 'produce'},
            {"name": 'lemon juice', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Greek yogurt parfait',
        "description": 'Layers of creamy Greek yogurt, crunchy granola, and fresh berries.',
        "instructions": 'Layer yogurt, granola, and berries in a glass or bowl. Drizzle with honey. Serve immediately.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 1,
        "calories": 495.8,
        "protein_g": 28.2,
        "carbs_g": 21.6,
        "fats_g": 21.0,
        "iron_mg": 4.6,
        "calcium_mg": 275.3,
        "vitamin_c_mg": 35.2,
        "vitamin_d_iu": 143.5,
        "ingredients": [
            {"name": 'Greek yogurt', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'granola', "quantity": 0.25, "unit": 'cup', "category": 'grains'},
            {"name": 'mixed berries', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Pasta salad with vegetables',
        "description": 'Colorful rotini pasta tossed with fresh vegetables and Italian dressing.',
        "instructions": 'Cook pasta and cool. Chop vegetables. Toss everything with Italian dressing. Chill before serving.',
        "meal_type": 'lunch',
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories": 642.4,
        "protein_g": 27.4,
        "carbs_g": 17.3,
        "fats_g": 23.7,
        "iron_mg": 3.7,
        "calcium_mg": 323.5,
        "vitamin_c_mg": 35.3,
        "vitamin_d_iu": 199.5,
        "ingredients": [
            {"name": 'rotini pasta', "quantity": 2.0, "unit": 'cup', "category": 'grains'},
            {"name": 'cherry tomatoes', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'cucumber', "quantity": 0.5, "unit": 'each', "category": 'produce'},
            {"name": 'bell pepper', "quantity": 0.5, "unit": 'each', "category": 'produce'},
            {"name": 'Italian dressing', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Grilled cheese and tomato soup',
        "description": 'Golden grilled cheese sandwich paired with warm creamy tomato soup.',
        "instructions": 'Butter bread and grill with cheese until golden. Heat tomato soup. Serve together.',
        "meal_type": 'lunch',
        "prep_time": 5,
        "cook_time": 15,
        "servings": 2,
        "calories": 486.4,
        "protein_g": 28.5,
        "carbs_g": 10.6,
        "fats_g": 10.2,
        "iron_mg": 5.2,
        "calcium_mg": 298.9,
        "vitamin_c_mg": 50.0,
        "vitamin_d_iu": 318.0,
        "ingredients": [
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'cheddar cheese', "quantity": 2.0, "unit": 'oz', "category": 'dairy'},
            {"name": 'butter', "quantity": 1.0, "unit": 'tbsp', "category": 'dairy'},
            {"name": 'tomato soup', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
        ],
    },
    {
        "name": 'Grilled chicken with rice and broccoli',
        "description": 'Lean grilled chicken breast with fluffy brown rice and steamed broccoli.',
        "instructions": 'Season and grill chicken. Cook rice. Steam broccoli. Plate together and season to taste.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "calories": 476.2,
        "protein_g": 24.9,
        "carbs_g": 22.4,
        "fats_g": 21.8,
        "iron_mg": 6.2,
        "calcium_mg": 274.0,
        "vitamin_c_mg": 41.8,
        "vitamin_d_iu": 201.9,
        "ingredients": [
            {"name": 'chicken breast', "quantity": 6.0, "unit": 'oz', "category": 'meat'},
            {"name": 'brown rice', "quantity": 1.0, "unit": 'cup', "category": 'grains'},
            {"name": 'broccoli', "quantity": 2.0, "unit": 'cup', "category": 'produce'},
            {"name": 'olive oil', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'garlic', "quantity": 2.0, "unit": 'clove', "category": 'produce'},
        ],
    },
    {
        "name": 'Salmon with sweet potato',
        "description": 'Oven-baked salmon fillet alongside roasted sweet potato.',
        "instructions": 'Season salmon and bake at 400°F for 12-15 min. Roast diced sweet potato. Serve with lemon.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "calories": 471.0,
        "protein_g": 25.3,
        "carbs_g": 27.5,
        "fats_g": 20.7,
        "iron_mg": 5.0,
        "calcium_mg": 157.2,
        "vitamin_c_mg": 30.8,
        "vitamin_d_iu": 290.4,
        "ingredients": [
            {"name": 'salmon fillet', "quantity": 6.0, "unit": 'oz', "category": 'meat'},
            {"name": 'sweet potato', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'olive oil', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'lemon', "quantity": 0.5, "unit": 'each', "category": 'produce'},
            {"name": 'garlic', "quantity": 2.0, "unit": 'clove', "category": 'produce'},
        ],
    },
    {
        "name": 'Turkey chili with beans',
        "description": 'Hearty turkey chili loaded with kidney beans and tomatoes.',
        "instructions": 'Brown turkey. Add onion, beans, tomatoes, and spices. Simmer 30 minutes. Serve hot.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 35,
        "servings": 6,
        "calories": 549.6,
        "protein_g": 28.1,
        "carbs_g": 15.7,
        "fats_g": 17.6,
        "iron_mg": 4.8,
        "calcium_mg": 245.4,
        "vitamin_c_mg": 46.4,
        "vitamin_d_iu": 152.6,
        "ingredients": [
            {"name": 'ground turkey', "quantity": 1.0, "unit": 'lb', "category": 'meat'},
            {"name": 'kidney beans', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'diced tomatoes', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
            {"name": 'chili powder', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'onion', "quantity": 0.5, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Beef stir fry with vegetables',
        "description": 'Tender beef strips stir-fried with colorful vegetables in savory sauce.',
        "instructions": 'Sauté beef in sesame oil. Add vegetables and soy sauce. Stir-fry 5-7 minutes. Serve over rice.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories": 604.6,
        "protein_g": 31.3,
        "carbs_g": 20.0,
        "fats_g": 16.8,
        "iron_mg": 4.1,
        "calcium_mg": 319.9,
        "vitamin_c_mg": 42.3,
        "vitamin_d_iu": 220.7,
        "ingredients": [
            {"name": 'beef strips', "quantity": 6.0, "unit": 'oz', "category": 'meat'},
            {"name": 'broccoli', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
            {"name": 'bell pepper', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'soy sauce', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'sesame oil', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Whole wheat spaghetti with meat sauce',
        "description": 'Hearty meat sauce over al dente whole wheat spaghetti.',
        "instructions": 'Brown beef with garlic. Add marinara. Simmer 20 min. Cook pasta. Toss and top with parmesan.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 30,
        "servings": 6,
        "calories": 518.8,
        "protein_g": 30.6,
        "carbs_g": 19.8,
        "fats_g": 15.8,
        "iron_mg": 6.1,
        "calcium_mg": 339.8,
        "vitamin_c_mg": 34.1,
        "vitamin_d_iu": 213.3,
        "ingredients": [
            {"name": 'whole wheat spaghetti', "quantity": 8.0, "unit": 'oz', "category": 'grains'},
            {"name": 'ground beef', "quantity": 0.5, "unit": 'lb', "category": 'meat'},
            {"name": 'marinara sauce', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'parmesan cheese', "quantity": 2.0, "unit": 'tbsp', "category": 'dairy'},
            {"name": 'garlic', "quantity": 2.0, "unit": 'clove', "category": 'produce'},
        ],
    },
    {
        "name": 'Chicken fajitas',
        "description": 'Sizzling chicken strips with peppers and onions served in warm flour tortillas.',
        "instructions": 'Season chicken and cook in skillet. Sauté peppers and onion. Serve in warmed tortillas.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "calories": 434.4,
        "protein_g": 23.1,
        "carbs_g": 23.4,
        "fats_g": 15.4,
        "iron_mg": 4.3,
        "calcium_mg": 270.7,
        "vitamin_c_mg": 43.0,
        "vitamin_d_iu": 109.9,
        "ingredients": [
            {"name": 'chicken breast', "quantity": 6.0, "unit": 'oz', "category": 'meat'},
            {"name": 'flour tortillas', "quantity": 3.0, "unit": 'each', "category": 'grains'},
            {"name": 'bell pepper', "quantity": 2.0, "unit": 'each', "category": 'produce'},
            {"name": 'onion', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'fajita seasoning', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Vegetable soup with bread',
        "description": 'Comforting vegetable soup simmered in rich broth with crusty bread.',
        "instructions": 'Sauté garlic in olive oil. Add broth and vegetables. Simmer 20 min. Serve with bread.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 25,
        "servings": 6,
        "calories": 507.4,
        "protein_g": 19.6,
        "carbs_g": 20.2,
        "fats_g": 24.4,
        "iron_mg": 4.9,
        "calcium_mg": 337.1,
        "vitamin_c_mg": 35.7,
        "vitamin_d_iu": 169.0,
        "ingredients": [
            {"name": 'mixed vegetables', "quantity": 2.0, "unit": 'cup', "category": 'produce'},
            {"name": 'vegetable broth', "quantity": 3.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'garlic', "quantity": 2.0, "unit": 'clove', "category": 'produce'},
            {"name": 'whole wheat bread', "quantity": 2.0, "unit": 'slice', "category": 'grains'},
            {"name": 'olive oil', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Baked chicken thighs with carrots',
        "description": 'Oven-roasted chicken thighs with tender herb-seasoned carrots.',
        "instructions": 'Season chicken and carrots with oil and herbs. Roast at 400°F for 35-40 min. Serve hot.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 40,
        "servings": 4,
        "calories": 606.0,
        "protein_g": 22.7,
        "carbs_g": 14.0,
        "fats_g": 23.5,
        "iron_mg": 4.5,
        "calcium_mg": 315.8,
        "vitamin_c_mg": 56.8,
        "vitamin_d_iu": 214.4,
        "ingredients": [
            {"name": 'chicken thighs', "quantity": 4.0, "unit": 'each', "category": 'meat'},
            {"name": 'carrots', "quantity": 3.0, "unit": 'each', "category": 'produce'},
            {"name": 'olive oil', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'garlic powder', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
            {"name": 'Italian herbs', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Shrimp and rice bowl',
        "description": 'Juicy sautéed shrimp over fluffy white rice with broccoli.',
        "instructions": 'Cook rice. Sauté shrimp in sesame oil with soy sauce. Steam broccoli. Layer in bowl.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "calories": 426.8,
        "protein_g": 23.0,
        "carbs_g": 23.0,
        "fats_g": 27.9,
        "iron_mg": 4.5,
        "calcium_mg": 285.5,
        "vitamin_c_mg": 35.0,
        "vitamin_d_iu": 200.5,
        "ingredients": [
            {"name": 'shrimp', "quantity": 6.0, "unit": 'oz', "category": 'meat'},
            {"name": 'white rice', "quantity": 1.0, "unit": 'cup', "category": 'grains'},
            {"name": 'broccoli', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
            {"name": 'soy sauce', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'sesame oil', "quantity": 1.0, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Lentil curry with rice',
        "description": 'Warming red lentil curry in coconut milk served over fluffy white rice.',
        "instructions": 'Sauté onion. Add lentils, coconut milk, and curry powder. Simmer 20 min. Serve over rice.',
        "meal_type": 'dinner',
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "calories": 514.2,
        "protein_g": 14.5,
        "carbs_g": 17.2,
        "fats_g": 21.8,
        "iron_mg": 3.8,
        "calcium_mg": 299.9,
        "vitamin_c_mg": 49.6,
        "vitamin_d_iu": 137.4,
        "ingredients": [
            {"name": 'red lentils', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'white rice', "quantity": 1.0, "unit": 'cup', "category": 'grains'},
            {"name": 'coconut milk', "quantity": 1.0, "unit": 'cup', "category": 'pantry'},
            {"name": 'curry powder', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'onion', "quantity": 1.0, "unit": 'each', "category": 'produce'},
        ],
    },
    {
        "name": 'Apple slices with peanut butter',
        "description": 'Crisp apple slices paired with creamy peanut butter for dipping.',
        "instructions": 'Slice apple into wedges. Serve with peanut butter for dipping.',
        "meal_type": 'snack',
        "prep_time": 3,
        "cook_time": 0,
        "servings": 1,
        "calories": 346.4,
        "protein_g": 32.7,
        "carbs_g": 23.2,
        "fats_g": 28.0,
        "iron_mg": 5.5,
        "calcium_mg": 227.8,
        "vitamin_c_mg": 41.2,
        "vitamin_d_iu": 170.6,
        "ingredients": [
            {"name": 'apple', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'peanut butter', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'String cheese and crackers',
        "description": 'Portable string cheese with whole grain crackers.',
        "instructions": 'Peel string cheese. Arrange with crackers on a plate. Serve.',
        "meal_type": 'snack',
        "prep_time": 2,
        "cook_time": 0,
        "servings": 1,
        "calories": 509.8,
        "protein_g": 27.7,
        "carbs_g": 25.4,
        "fats_g": 20.6,
        "iron_mg": 3.8,
        "calcium_mg": 314.0,
        "vitamin_c_mg": 38.9,
        "vitamin_d_iu": 213.9,
        "ingredients": [
            {"name": 'string cheese', "quantity": 2.0, "unit": 'oz', "category": 'dairy'},
            {"name": 'whole grain crackers', "quantity": 1.0, "unit": 'oz', "category": 'grains'},
        ],
    },
    {
        "name": 'Trail mix',
        "description": 'A mix of nuts, dried cranberries, and dark chocolate chips.',
        "instructions": 'Combine all ingredients in a bowl or bag. Serve.',
        "meal_type": 'snack',
        "prep_time": 3,
        "cook_time": 0,
        "servings": 1,
        "calories": 571.8,
        "protein_g": 18.4,
        "carbs_g": 19.9,
        "fats_g": 23.0,
        "iron_mg": 5.3,
        "calcium_mg": 329.2,
        "vitamin_c_mg": 48.6,
        "vitamin_d_iu": 235.8,
        "ingredients": [
            {"name": 'mixed nuts', "quantity": 0.25, "unit": 'cup', "category": 'pantry'},
            {"name": 'dried cranberries', "quantity": 2.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'dark chocolate chips', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Greek yogurt cup',
        "description": 'Simple creamy Greek yogurt drizzled with honey.',
        "instructions": 'Scoop yogurt into a cup. Drizzle with honey. Serve.',
        "meal_type": 'snack',
        "prep_time": 2,
        "cook_time": 0,
        "servings": 1,
        "calories": 443.6,
        "protein_g": 20.2,
        "carbs_g": 16.8,
        "fats_g": 19.5,
        "iron_mg": 4.4,
        "calcium_mg": 236.7,
        "vitamin_c_mg": 45.0,
        "vitamin_d_iu": 197.3,
        "ingredients": [
            {"name": 'Greek yogurt', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'honey', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Banana with almonds',
        "description": 'A banana paired with a handful of almonds.',
        "instructions": 'Peel banana. Portion almonds. Serve together.',
        "meal_type": 'snack',
        "prep_time": 2,
        "cook_time": 0,
        "servings": 1,
        "calories": 413.6,
        "protein_g": 25.0,
        "carbs_g": 21.4,
        "fats_g": 25.9,
        "iron_mg": 5.6,
        "calcium_mg": 172.5,
        "vitamin_c_mg": 36.6,
        "vitamin_d_iu": 205.9,
        "ingredients": [
            {"name": 'banana', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'almonds', "quantity": 1.0, "unit": 'oz', "category": 'pantry'},
        ],
    },
    {
        "name": 'Hummus with carrots',
        "description": 'Smooth hummus served with crisp baby carrots for dipping.',
        "instructions": 'Portion hummus into a bowl. Arrange carrots alongside for dipping.',
        "meal_type": 'snack',
        "prep_time": 3,
        "cook_time": 0,
        "servings": 1,
        "calories": 359.0,
        "protein_g": 20.7,
        "carbs_g": 8.4,
        "fats_g": 22.1,
        "iron_mg": 4.5,
        "calcium_mg": 184.5,
        "vitamin_c_mg": 49.2,
        "vitamin_d_iu": 156.1,
        "ingredients": [
            {"name": 'hummus', "quantity": 0.25, "unit": 'cup', "category": 'pantry'},
            {"name": 'baby carrots', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
        ],
    },
    {
        "name": 'Boiled eggs',
        "description": 'Simple hard-boiled eggs lightly seasoned with salt.',
        "instructions": 'Place eggs in cold water. Bring to boil. Cook 10-12 min. Cool and peel. Season with salt.',
        "meal_type": 'snack',
        "prep_time": 2,
        "cook_time": 12,
        "servings": 2,
        "calories": 560.2,
        "protein_g": 24.5,
        "carbs_g": 16.4,
        "fats_g": 23.9,
        "iron_mg": 4.6,
        "calcium_mg": 187.9,
        "vitamin_c_mg": 51.8,
        "vitamin_d_iu": 170.3,
        "ingredients": [
            {"name": 'eggs', "quantity": 2.0, "unit": 'each', "category": 'meat'},
            {"name": 'salt', "quantity": 0.25, "unit": 'tsp', "category": 'pantry'},
        ],
    },
    {
        "name": 'Fruit smoothie',
        "description": 'A refreshing blend of berries, banana, and orange juice.',
        "instructions": 'Add all ingredients to a blender. Blend until smooth. Serve immediately.',
        "meal_type": 'snack',
        "prep_time": 5,
        "cook_time": 0,
        "servings": 1,
        "calories": 450.8,
        "protein_g": 27.8,
        "carbs_g": 15.9,
        "fats_g": 29.0,
        "iron_mg": 3.9,
        "calcium_mg": 279.1,
        "vitamin_c_mg": 46.6,
        "vitamin_d_iu": 123.0,
        "ingredients": [
            {"name": 'mixed berries', "quantity": 1.0, "unit": 'cup', "category": 'produce'},
            {"name": 'banana', "quantity": 1.0, "unit": 'each', "category": 'produce'},
            {"name": 'orange juice', "quantity": 0.5, "unit": 'cup', "category": 'produce'},
            {"name": 'yogurt', "quantity": 0.5, "unit": 'cup', "category": 'dairy'},
        ],
    },
    {
        "name": 'Cottage cheese cup',
        "description": 'Creamy cottage cheese with a sweet fruit topping.',
        "instructions": 'Scoop cottage cheese into a cup. Add fruit topping. Serve.',
        "meal_type": 'snack',
        "prep_time": 3,
        "cook_time": 0,
        "servings": 1,
        "calories": 352.2,
        "protein_g": 26.4,
        "carbs_g": 14.2,
        "fats_g": 20.6,
        "iron_mg": 6.5,
        "calcium_mg": 248.9,
        "vitamin_c_mg": 65.7,
        "vitamin_d_iu": 180.7,
        "ingredients": [
            {"name": 'cottage cheese', "quantity": 1.0, "unit": 'cup', "category": 'dairy'},
            {"name": 'fruit topping', "quantity": 0.25, "unit": 'cup', "category": 'produce'},
        ],
    },
    {
        "name": 'Popcorn',
        "description": 'Light and crunchy air-popped popcorn seasoned with a touch of salt.',
        "instructions": 'Heat oil in pot. Add kernels and cover. Shake until popping slows. Season with salt.',
        "meal_type": 'snack',
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 584.6,
        "protein_g": 25.9,
        "carbs_g": 26.3,
        "fats_g": 27.0,
        "iron_mg": 5.1,
        "calcium_mg": 303.8,
        "vitamin_c_mg": 48.5,
        "vitamin_d_iu": 252.4,
        "ingredients": [
            {"name": 'popcorn kernels', "quantity": 0.25, "unit": 'cup', "category": 'grains'},
            {"name": 'olive oil', "quantity": 1.0, "unit": 'tbsp', "category": 'pantry'},
            {"name": 'salt', "quantity": 0.25, "unit": 'tsp', "category": 'pantry'},
        ],
    },
]


def seed_meals(db):
    if db.query(Meal).count() > 0:
        return
    for m in MEAL_DATA:
        meal = Meal(
            name=m["name"],
            description=m["description"],
            instructions=m["instructions"],
            meal_type=m["meal_type"],
            prep_time=m["prep_time"],
            cook_time=m["cook_time"],
            servings=m["servings"],
            calories=m.get("calories"),
            protein_g=m.get("protein_g"),
            carbs_g=m.get("carbs_g"),
            fats_g=m.get("fats_g"),
            iron_mg=m.get("iron_mg"),
            calcium_mg=m.get("calcium_mg"),
            vitamin_c_mg=m.get("vitamin_c_mg"),
            vitamin_d_iu=m.get("vitamin_d_iu"),
        )
        db.add(meal)
        db.flush()
        for ing in m["ingredients"]:
            db.add(MealIngredient(
                meal_id=meal.id,
                name=ing["name"],
                quantity=ing["quantity"],
                unit=ing["unit"],
                category=ing["category"],
            ))
    db.commit()
