from sqlalchemy.orm import Session
from .models import Meal, MealIngredient


MEALS = [
    {
        "name": "Overnight Oats",
        "description": "No-cook oats soaked overnight, topped with fresh fruit. Great for busy school mornings.",
        "instructions": "1. Combine 1/2 cup oats with 1/2 cup milk and 1/4 cup yogurt in a jar.\n2. Add honey and stir well.\n3. Cover and refrigerate overnight.\n4. Top with banana slices and berries before serving.",
        "meal_type": "breakfast",
        "prep_time": 5,
        "cook_time": 0,
        "servings": 1,
        "ingredients": [
            {"name": "rolled oats", "quantity": 0.5, "unit": "cup", "category": "grains"},
            {"name": "milk", "quantity": 0.5, "unit": "cup", "category": "dairy"},
            {"name": "Greek yogurt", "quantity": 0.25, "unit": "cup", "category": "dairy"},
            {"name": "honey", "quantity": 1, "unit": "tbsp", "category": "pantry"},
            {"name": "banana", "quantity": 1, "unit": "medium", "category": "produce"},
            {"name": "mixed berries", "quantity": 0.25, "unit": "cup", "category": "produce"},
        ],
    },
    {
        "name": "Scrambled Eggs & Toast",
        "description": "Fluffy scrambled eggs with whole wheat toast. Simple protein-packed breakfast for the whole family.",
        "instructions": "1. Crack eggs into a bowl, add milk, salt and pepper, whisk well.\n2. Heat butter in a pan over medium-low heat.\n3. Add eggs and stir gently until just set.\n4. Toast bread slices.\n5. Serve eggs on toast with optional sliced tomatoes.",
        "meal_type": "breakfast",
        "prep_time": 5,
        "cook_time": 8,
        "servings": 4,
        "ingredients": [
            {"name": "eggs", "quantity": 8, "unit": "large", "category": "dairy"},
            {"name": "milk", "quantity": 0.25, "unit": "cup", "category": "dairy"},
            {"name": "butter", "quantity": 1, "unit": "tbsp", "category": "dairy"},
            {"name": "whole wheat bread", "quantity": 8, "unit": "slices", "category": "grains"},
            {"name": "salt", "quantity": 0.5, "unit": "tsp", "category": "pantry"},
            {"name": "tomato", "quantity": 1, "unit": "medium", "category": "produce"},
        ],
    },
    {
        "name": "Banana Oat Pancakes",
        "description": "Fluffy pancakes made with mashed banana and oats — naturally sweet and kid-approved!",
        "instructions": "1. Mash 2 ripe bananas in a bowl.\n2. Mix in 2 eggs, 1 cup oats, 1 tsp baking powder, and a pinch of cinnamon.\n3. Heat a lightly oiled griddle over medium heat.\n4. Pour batter in small circles, cook 2–3 min per side until golden.\n5. Serve with maple syrup or fresh fruit.",
        "meal_type": "breakfast",
        "prep_time": 10,
        "cook_time": 15,
        "servings": 4,
        "ingredients": [
            {"name": "ripe bananas", "quantity": 2, "unit": "medium", "category": "produce"},
            {"name": "eggs", "quantity": 2, "unit": "large", "category": "dairy"},
            {"name": "rolled oats", "quantity": 1, "unit": "cup", "category": "grains"},
            {"name": "baking powder", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "cinnamon", "quantity": 0.5, "unit": "tsp", "category": "pantry"},
            {"name": "maple syrup", "quantity": 2, "unit": "tbsp", "category": "pantry"},
            {"name": "cooking oil", "quantity": 1, "unit": "tsp", "category": "pantry"},
        ],
    },
    {
        "name": "Turkey & Cheese Wraps",
        "description": "Easy school lunch wraps with turkey, cheese, and crunchy veggies. Pack in 5 minutes!",
        "instructions": "1. Lay tortilla flat and spread with a thin layer of mustard or mayo.\n2. Layer turkey slices, cheese, lettuce, and cucumber strips.\n3. Roll tightly and slice in half.\n4. Wrap in parchment paper for lunchbox.",
        "meal_type": "lunch",
        "prep_time": 5,
        "cook_time": 0,
        "servings": 4,
        "ingredients": [
            {"name": "flour tortillas", "quantity": 4, "unit": "large", "category": "grains"},
            {"name": "sliced turkey deli meat", "quantity": 8, "unit": "oz", "category": "meat"},
            {"name": "cheddar cheese slices", "quantity": 4, "unit": "slices", "category": "dairy"},
            {"name": "romaine lettuce", "quantity": 1, "unit": "cup", "category": "produce"},
            {"name": "cucumber", "quantity": 1, "unit": "medium", "category": "produce"},
            {"name": "mustard", "quantity": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "name": "PB&J Sandwiches",
        "description": "Classic peanut butter and jelly sandwiches — a school lunchbox staple. Quick to make the night before.",
        "instructions": "1. Spread peanut butter on one slice of bread.\n2. Spread jam on the other slice.\n3. Press together, cut diagonally.\n4. Pair with an apple and some carrot sticks.",
        "meal_type": "lunch",
        "prep_time": 5,
        "cook_time": 0,
        "servings": 4,
        "ingredients": [
            {"name": "whole wheat bread", "quantity": 8, "unit": "slices", "category": "grains"},
            {"name": "peanut butter", "quantity": 0.5, "unit": "cup", "category": "pantry"},
            {"name": "strawberry jam", "quantity": 0.25, "unit": "cup", "category": "pantry"},
            {"name": "apple", "quantity": 4, "unit": "medium", "category": "produce"},
            {"name": "baby carrots", "quantity": 1, "unit": "cup", "category": "produce"},
        ],
    },
    {
        "name": "Grilled Cheese & Tomato Soup",
        "description": "Golden buttery grilled cheese paired with creamy tomato soup. A comfort lunch for all ages.",
        "instructions": "1. Heat tomato soup in a pot over medium heat, stirring occasionally.\n2. Butter one side of each bread slice.\n3. Place butter-side down in a pan, add cheese slices, top with second bread slice butter-side up.\n4. Cook 2–3 min per side until golden and cheese is melted.\n5. Slice diagonally and serve with hot soup.",
        "meal_type": "lunch",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 4,
        "ingredients": [
            {"name": "canned tomato soup", "quantity": 2, "unit": "cans (10.75 oz)", "category": "pantry"},
            {"name": "white bread", "quantity": 8, "unit": "slices", "category": "grains"},
            {"name": "cheddar cheese slices", "quantity": 8, "unit": "slices", "category": "dairy"},
            {"name": "butter", "quantity": 4, "unit": "tbsp", "category": "dairy"},
            {"name": "milk", "quantity": 0.5, "unit": "cup", "category": "dairy"},
        ],
    },
    {
        "name": "Creamy Mac & Cheese",
        "description": "Homemade stovetop mac and cheese — way better than the box. Kids devour it every time.",
        "instructions": "1. Cook macaroni according to package instructions, drain.\n2. In the same pot, melt butter over medium heat.\n3. Whisk in flour and cook 1 min.\n4. Gradually whisk in milk until smooth and thickened (about 5 min).\n5. Remove from heat, stir in cheese until melted.\n6. Add macaroni, season with salt and mustard powder. Stir and serve.",
        "meal_type": "lunch",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 6,
        "ingredients": [
            {"name": "elbow macaroni", "quantity": 16, "unit": "oz", "category": "grains"},
            {"name": "butter", "quantity": 3, "unit": "tbsp", "category": "dairy"},
            {"name": "all-purpose flour", "quantity": 3, "unit": "tbsp", "category": "pantry"},
            {"name": "whole milk", "quantity": 2.5, "unit": "cups", "category": "dairy"},
            {"name": "shredded cheddar cheese", "quantity": 2, "unit": "cups", "category": "dairy"},
            {"name": "salt", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "dry mustard powder", "quantity": 0.5, "unit": "tsp", "category": "pantry"},
        ],
    },
    {
        "name": "Chicken Stir Fry with Rice",
        "description": "Quick weeknight stir fry packed with colorful veggies and tender chicken over fluffy rice.",
        "instructions": "1. Cook rice per package instructions.\n2. Cut chicken into thin strips, season with salt and pepper.\n3. Heat oil in a wok or large pan over high heat. Cook chicken 5–6 min until cooked through. Remove.\n4. Add vegetables to pan, stir fry 3–4 min.\n5. Return chicken, add soy sauce, garlic, ginger. Toss to combine.\n6. Serve over rice.",
        "meal_type": "dinner",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 6,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lbs", "category": "meat"},
            {"name": "long grain white rice", "quantity": 2, "unit": "cups", "category": "grains"},
            {"name": "broccoli florets", "quantity": 2, "unit": "cups", "category": "produce"},
            {"name": "bell pepper", "quantity": 2, "unit": "medium", "category": "produce"},
            {"name": "carrots", "quantity": 2, "unit": "medium", "category": "produce"},
            {"name": "soy sauce", "quantity": 0.25, "unit": "cup", "category": "pantry"},
            {"name": "garlic", "quantity": 3, "unit": "cloves", "category": "produce"},
            {"name": "fresh ginger", "quantity": 1, "unit": "tsp", "category": "produce"},
            {"name": "vegetable oil", "quantity": 2, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "name": "Spaghetti Bolognese",
        "description": "A hearty Italian meat sauce over spaghetti. Make a big batch and freeze leftovers for easy meals.",
        "instructions": "1. Cook spaghetti in salted boiling water until al dente. Drain.\n2. Brown ground beef in a large pan over medium-high heat. Drain excess fat.\n3. Add diced onion and garlic, cook 3 min.\n4. Add crushed tomatoes, tomato paste, Italian seasoning, salt and pepper.\n5. Simmer 20 min, stirring occasionally.\n6. Serve sauce over spaghetti, top with Parmesan.",
        "meal_type": "dinner",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 8,
        "ingredients": [
            {"name": "spaghetti", "quantity": 1, "unit": "lb", "category": "grains"},
            {"name": "ground beef (85% lean)", "quantity": 1.5, "unit": "lbs", "category": "meat"},
            {"name": "onion", "quantity": 1, "unit": "large", "category": "produce"},
            {"name": "garlic", "quantity": 4, "unit": "cloves", "category": "produce"},
            {"name": "crushed tomatoes", "quantity": 28, "unit": "oz can", "category": "pantry"},
            {"name": "tomato paste", "quantity": 2, "unit": "tbsp", "category": "pantry"},
            {"name": "Italian seasoning", "quantity": 2, "unit": "tsp", "category": "pantry"},
            {"name": "Parmesan cheese", "quantity": 0.5, "unit": "cup", "category": "dairy"},
        ],
    },
    {
        "name": "Baked Chicken Thighs & Roasted Vegetables",
        "description": "Juicy oven-baked chicken thighs with colorful roasted vegetables. One pan, minimal effort.",
        "instructions": "1. Preheat oven to 425°F.\n2. Toss vegetables with olive oil, salt, pepper, and garlic powder on a sheet pan.\n3. Season chicken thighs with paprika, garlic powder, salt and pepper.\n4. Place chicken on top of vegetables.\n5. Roast 35–40 min until chicken is golden and cooked through (internal temp 165°F).\n6. Rest 5 min before serving.",
        "meal_type": "dinner",
        "prep_time": 15,
        "cook_time": 40,
        "servings": 6,
        "ingredients": [
            {"name": "bone-in chicken thighs", "quantity": 6, "unit": "pieces", "category": "meat"},
            {"name": "baby potatoes", "quantity": 1, "unit": "lb", "category": "produce"},
            {"name": "zucchini", "quantity": 2, "unit": "medium", "category": "produce"},
            {"name": "cherry tomatoes", "quantity": 1, "unit": "cup", "category": "produce"},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp", "category": "pantry"},
            {"name": "paprika", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "garlic powder", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "salt", "quantity": 1, "unit": "tsp", "category": "pantry"},
        ],
    },
    {
        "name": "Taco Bowl",
        "description": "Build-your-own taco bowls with seasoned beef, rice, beans, and all the toppings. Everyone customizes their own!",
        "instructions": "1. Cook rice per instructions.\n2. Brown ground beef in a pan, drain fat.\n3. Add taco seasoning and water per packet directions. Simmer 5 min.\n4. Warm black beans in a small pot.\n5. Set up toppings bar: cheese, sour cream, salsa, guacamole, lettuce.\n6. Build bowls with rice base, beef, beans, and desired toppings.",
        "meal_type": "dinner",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 6,
        "ingredients": [
            {"name": "ground beef (85% lean)", "quantity": 1.5, "unit": "lbs", "category": "meat"},
            {"name": "taco seasoning", "quantity": 1, "unit": "packet", "category": "pantry"},
            {"name": "long grain white rice", "quantity": 2, "unit": "cups", "category": "grains"},
            {"name": "black beans", "quantity": 15, "unit": "oz can", "category": "pantry"},
            {"name": "shredded cheddar cheese", "quantity": 1, "unit": "cup", "category": "dairy"},
            {"name": "sour cream", "quantity": 0.5, "unit": "cup", "category": "dairy"},
            {"name": "salsa", "quantity": 1, "unit": "cup", "category": "pantry"},
            {"name": "romaine lettuce", "quantity": 2, "unit": "cups", "category": "produce"},
            {"name": "avocado", "quantity": 2, "unit": "medium", "category": "produce"},
        ],
    },
    {
        "name": "Baked Salmon with Quinoa & Broccoli",
        "description": "Omega-3-rich salmon with protein-packed quinoa and steamed broccoli. Great for brain development and energy.",
        "instructions": "1. Preheat oven to 400°F.\n2. Cook quinoa per package instructions.\n3. Place salmon fillets on a lined baking sheet, season with lemon juice, olive oil, garlic, salt.\n4. Bake 12–15 min until flakes easily with a fork.\n5. Steam broccoli until tender, 5 min.\n6. Serve salmon over quinoa with broccoli on the side.",
        "meal_type": "dinner",
        "prep_time": 10,
        "cook_time": 20,
        "servings": 4,
        "ingredients": [
            {"name": "salmon fillets", "quantity": 4, "unit": "6oz fillets", "category": "meat"},
            {"name": "quinoa", "quantity": 1.5, "unit": "cups", "category": "grains"},
            {"name": "broccoli", "quantity": 4, "unit": "cups", "category": "produce"},
            {"name": "lemon", "quantity": 1, "unit": "medium", "category": "produce"},
            {"name": "olive oil", "quantity": 2, "unit": "tbsp", "category": "pantry"},
            {"name": "garlic", "quantity": 2, "unit": "cloves", "category": "produce"},
            {"name": "salt", "quantity": 0.5, "unit": "tsp", "category": "pantry"},
        ],
    },
    {
        "name": "Vegetable Beef Soup",
        "description": "Hearty and nourishing beef and vegetable soup. Easy to modify for toddlers — just mash the veggies!",
        "instructions": "1. Brown beef stew meat in a large pot with oil over medium-high heat.\n2. Add diced onion, celery, and carrots. Cook 5 min.\n3. Add diced potatoes, canned tomatoes, beef broth, and seasonings.\n4. Bring to a boil, reduce heat, simmer 45 min until beef is tender.\n5. Adjust seasoning. For toddlers, remove a portion and mash vegetables before serving.",
        "meal_type": "dinner",
        "prep_time": 15,
        "cook_time": 60,
        "servings": 8,
        "ingredients": [
            {"name": "beef stew meat", "quantity": 1.5, "unit": "lbs", "category": "meat"},
            {"name": "onion", "quantity": 1, "unit": "large", "category": "produce"},
            {"name": "celery", "quantity": 3, "unit": "stalks", "category": "produce"},
            {"name": "carrots", "quantity": 3, "unit": "large", "category": "produce"},
            {"name": "potatoes", "quantity": 3, "unit": "medium", "category": "produce"},
            {"name": "diced tomatoes", "quantity": 14, "unit": "oz can", "category": "pantry"},
            {"name": "beef broth", "quantity": 6, "unit": "cups", "category": "pantry"},
            {"name": "Italian seasoning", "quantity": 1, "unit": "tsp", "category": "pantry"},
        ],
    },
    {
        "name": "Homemade Pizza",
        "description": "Fun family pizza night! Use store-bought dough for easy prep and let the kids add their own toppings.",
        "instructions": "1. Preheat oven to 450°F. If using pizza stone, heat it too.\n2. Roll out pizza dough on a floured surface.\n3. Spread marinara sauce, leaving 1-inch border.\n4. Scatter mozzarella cheese evenly.\n5. Add desired toppings.\n6. Bake 10–14 min until crust is golden and cheese is bubbly.\n7. Cool 5 min before slicing.",
        "meal_type": "dinner",
        "prep_time": 20,
        "cook_time": 14,
        "servings": 6,
        "ingredients": [
            {"name": "store-bought pizza dough", "quantity": 1, "unit": "lb", "category": "grains"},
            {"name": "marinara sauce", "quantity": 1, "unit": "cup", "category": "pantry"},
            {"name": "shredded mozzarella cheese", "quantity": 2, "unit": "cups", "category": "dairy"},
            {"name": "bell pepper", "quantity": 1, "unit": "medium", "category": "produce"},
            {"name": "mushrooms", "quantity": 1, "unit": "cup", "category": "produce"},
            {"name": "pepperoni slices", "quantity": 2, "unit": "oz", "category": "meat"},
            {"name": "olive oil", "quantity": 1, "unit": "tbsp", "category": "pantry"},
        ],
    },
    {
        "name": "Sheet Pan Chicken Fajitas",
        "description": "Colorful and flavorful fajitas made entirely on one sheet pan. Easy cleanup, big flavor.",
        "instructions": "1. Preheat oven to 425°F.\n2. Slice chicken breasts and peppers into strips.\n3. Toss chicken and vegetables with olive oil, cumin, chili powder, garlic powder, salt.\n4. Spread on sheet pan in a single layer.\n5. Roast 20–25 min until chicken is cooked and edges are slightly charred.\n6. Serve in warm tortillas with toppings.",
        "meal_type": "dinner",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 6,
        "ingredients": [
            {"name": "chicken breast", "quantity": 1.5, "unit": "lbs", "category": "meat"},
            {"name": "bell peppers (mixed colors)", "quantity": 3, "unit": "large", "category": "produce"},
            {"name": "onion", "quantity": 1, "unit": "large", "category": "produce"},
            {"name": "flour tortillas", "quantity": 12, "unit": "small", "category": "grains"},
            {"name": "olive oil", "quantity": 3, "unit": "tbsp", "category": "pantry"},
            {"name": "cumin", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "chili powder", "quantity": 1, "unit": "tsp", "category": "pantry"},
            {"name": "garlic powder", "quantity": 0.5, "unit": "tsp", "category": "pantry"},
            {"name": "sour cream", "quantity": 0.5, "unit": "cup", "category": "dairy"},
            {"name": "lime", "quantity": 1, "unit": "medium", "category": "produce"},
        ],
    },
]


def seed_meals(db: Session):
    if db.query(Meal).count() > 0:
        return
    for meal_data in MEALS:
        ingredients = meal_data.pop("ingredients")
        meal = Meal(**meal_data)
        db.add(meal)
        db.flush()
        for ing in ingredients:
            db.add(MealIngredient(meal_id=meal.id, **ing))
    db.commit()
